# Generated by Django 5.0 on 2023-12-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='1996-05-02', verbose_name="Date d'anniversaire"),
            preserve_default=False,
        ),
    ]
