# Generated by Django 4.2.7 on 2023-12-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_contributor_projects_alter_contributor_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='projects',
        ),
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='projects_contributed_to', to='projects.contributor'),
        ),
    ]
