# Generated by Django 5.0 on 2023-12-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_issues_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contributors',
        ),
    ]
