# Generated by Django 4.2.7 on 2023-12-07 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_contributor_projects_alter_contributor_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='issues',
            field=models.ManyToManyField(blank=True, related_name='contributor_issues', to='projects.issues'),
        ),
        migrations.AddField(
            model_name='issues',
            name='contributor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_contributor', to='projects.contributor'),
        ),
        migrations.AddField(
            model_name='issues',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='issues',
            name='name',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='issues',
            name='nature',
            field=models.CharField(choices=[('BU', 'Bug'), ('FE', 'Feature'), ('TA', 'Task')], default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('LO', 'Low'), ('ME', 'Medium'), ('HI', 'High')], default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='issues',
            name='progression',
            field=models.CharField(choices=[('TD', 'To-Do'), ('IP', 'In progress'), ('FI', 'Finished')], default='TD', max_length=2),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='contributor_projects', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issues',
            name='projects',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_project', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='project_contributors', to='projects.contributor'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_projects', to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='contributor',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='contributor_comments', to='projects.comment'),
        ),
    ]
