# Generated by Django 4.2.7 on 2023-12-09 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_contributor_issues_issues_contributor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_issue', to='projects.issues')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AlterField(
            model_name='contributor',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='contributor_comments', to='projects.comments'),
        ),
    ]
